In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Make results more reproducible
tf.keras.utils.set_random_seed(42)

In [6]:
df = pd.read_csv(r"C:\Users\prana\Downloads\Churn_Modelling.csv")

print("Dataset shape:", df.shape)

display(df.head())

Dataset shape: (10000, 14)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df = df.drop(
    columns=["RowNumber", "CustomerId", "Surname"]
)

print("Remaining columns:")
print(df.columns)

Remaining columns:
Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [8]:
X = df.drop(columns=["Exited"])

y = df["Exited"].astype(int)

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (10000, 10)
Target shape: (10000,)

In [9]:
X = pd.get_dummies(
    X,
    columns=["Geography", "Gender"],
    drop_first=True,
    dtype=int
)

print("Feature shape after encoding:", X.shape)

display(X.head())

Feature shape after encoding: (10000, 11)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 8000
Testing samples: 2000

In [11]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

print("Normalization completed.")

Normalization completed.

In [12]:
model = tf.keras.Sequential()

# First hidden layer
model.add(
    tf.keras.layers.Dense(
        32,
        activation="relu",
        input_shape=(X_train.shape[1],)
    )
)

# Dropout to reduce overfitting
model.add(
    tf.keras.layers.Dropout(0.2)
)

# Second hidden layer
model.add(
    tf.keras.layers.Dense(
        16,
        activation="relu"
    )
)

# Output layer
model.add(
    tf.keras.layers.Dense(
        1,
        activation="sigmoid"
    )
)

C:\Users\prana\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           384 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 929 (3.63 KB)

 Trainable params: 929 (3.63 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
history = model.fit(
    X_train,
    y_train,
    epochs=15,
    batch_size=128,
    validation_split=0.1
)

print("Training completed.")

Epoch 1/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.7097 - loss: 0.6039 - val_accuracy: 0.8100 - val_loss: 0.4878
Epoch 2/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7954 - loss: 0.4931 - val_accuracy: 0.8112 - val_loss: 0.4397
Epoch 3/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4564 - val_accuracy: 0.8150 - val_loss: 0.4185
Epoch 4/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.4436 - val_accuracy: 0.8313 - val_loss: 0.4079
Epoch 5/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8136 - loss: 0.4323 - val_accuracy: 0.8363 - val_loss: 0.3993
Epoch 6/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8175 - loss: 0.4226 - val_accuracy: 0.8413 - val_loss: 0.3907
Epoch 7/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8238 - loss: 0.4169 - val_accuracy: 0.8450 - val_loss: 0.3816
Epoch 8/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8286 - loss: 0.4113 - val_accuracy: 0.8462 - val_loss: 0.3716
Epoch 9/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8344 - loss: 0.4005 - val_accuracy: 0.8550 - val_loss: 0.3618
Epoch 10/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8372 - loss: 0.3930 - val_accuracy: 0.8537 - val_loss: 0.3537
Epoch 11/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8436 - loss: 0.3851 - val_accuracy: 0.8600 - val_loss: 0.3461
Epoch 12/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8462 - loss: 0.3803 - val_accuracy: 0.8612 - val_loss: 0.3401
Epoch 13/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8426 - loss: 0.3792 - val_accuracy: 0.8650 - val_loss: 0.3364
Epoch 14/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8485 - loss: 0.3742 - val_accuracy: 0.8637 - val_loss: 0.3326
Epoch 15/15
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8450 - loss: 0.3703 - val_accuracy: 0.8637 - val_loss: 0.3298
Training completed.

In [17]:
probabilities = model.predict(X_test)

y_pred = (probabilities >= 0.5).astype(int)

y_pred = y_pred.ravel()

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [18]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy, 4))

Accuracy: 0.855

In [19]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[1552   41]
 [ 249  158]]